name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Build - Windows x86
      run: go build -ldflags="-s -w" -o dist/windows_x86/http-server.exe -v .
      env:
        GOOS: windows
        GOARCH: 386

    - name: Build - Windows x64
      run: go build -ldflags="-s -w" -o dist/windows_x64/http-server.exe -v .
      env:
        GOOS: windows
        GOARCH: amd64

    - name: Build - macOS x64
      run: go build -ldflags="-s -w" -o dist/macos/http-server -v .
      env:
        GOOS: darwin
        GOARCH: amd64

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist
